sunindex:
    path:     /
    defaults: { _controller: "ShipCruiseBundle:SunIndex:index" }

sunindex_show:
    path:     /{id}/show
    defaults: { _controller: "ShipCruiseBundle:SunIndex:show" }

sunindex_new:
    path:     /new
    defaults: { _controller: "ShipCruiseBundle:SunIndex:new" }

sunindex_create:
    path:     /create
    defaults: { _controller: "ShipCruiseBundle:SunIndex:create" }
    methods:  POST

sunindex_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShipCruiseBundle:SunIndex:edit" }

sunindex_update:
    path:     /{id}/update
    defaults: { _controller: "ShipCruiseBundle:SunIndex:update" }
    methods:  [POST, PUT]

sunindex_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShipCruiseBundle:SunIndex:delete" }
    methods:  [POST, DELETE]
