Ship\CruiseBundle\Entity\CruiseLine:
    type: entity
    table: cruise_line
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        cruiseLine:
            type: string
            length: 255
    oneToMany:
        ship:
            targetEntity: Ship
            mappedBy: cruiseLine
        route:
            targetEntity: Route
            mappedBy: cruiseLine
        cabin:
            targetEntity: CabinRecommendation
            mappedBy: cruiseLine
