Ship\CruiseBundle\Entity\Route:
    type: entity
    table: route
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        route:
            type: string
            length: 255
    oneToMany:
        sunIndex:
            targetEntity: SunIndex
            mappedBy: cruiseLine
        cabin:
            targetEntity: CabinRecommendation
            mappedBy: cruiseLine
    manyToOne:
        cruiseLine:
            targetEntity: CruiseLine
            inversedBy: route
#            nullable: true
            joinColumn:
                name: cruise_line_id
                referencedColumnName: id
        ship:
            targetEntity: Ship
            inversedBy: route
#            nullable: true
            joinColumn:
                name: ship_id
                referencedColumnName: id