Ship\CruiseBundle\Entity\SunIndex:
    type: entity
    table: sun_index
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        sunindex:
            type: string
            length: 255
